# This is a basic workflow to help you get started with Actions

name: ADempiere-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ "feature/#GH-Add-Actions" ]
  pull_request:
    branches: [ "feature/#GH-Add-Actions" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Build ADempiere with ant
      - name: Build Adempiere ...
        run: |
           echo $GITHUB_REF
           echo $GITHUB_HEAD_REF
           echo $GITHUB_BASE_REF
           echo ${{ github.ref }}
           cd utils_dev
           ant complete
      # Create ZIP Artifact for Download
      - name: adempiere-artifact
        uses: actions/upload-artifact@v2
        with:
          name: Adempiere.zip
          path: |
            install/build/*.tar.gz
            install/build/*.tar.gz.MD5
            install/build/*.zip
            install/build/*.zip.MD5
